import React from "react";
import Link from "next/link";
import Head from "next/head";

const HomePage = () => {
  return (
    <div className="video-container">
      <Head>
        <title>NeelB - Portfolio 🎧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./globals.css" />
      </Head>
      <video
        autoPlay
        loop
        muted
        className="video-background"
      >
        <source src="bg.webm" type="video/webm" />
      </video>
      <div className="center-button">
        <Link href="/portfolio">
          <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
            <span className="text-white">Portfolio ⛩️</span>
          </button>
        </Link>
      </div>
    </div>
  );
};

export default HomePage;
