import React from 'react';
import Typed from 'typed.js';
import Head from "next/head";
import Link from "next/link";
import { motion as m} from "framer-motion";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState, useRef, useEffect } from "react";
import devNeelB from "../public/devNeelB.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const el = React.useRef(null);

  const [isRotated, setIsRotated] = useState(false);

  const handleResumeDownload = () => {
  
    const resumeFile = 'resume.pdf';

    const tempLink = document.createElement('a');
    tempLink.href = resumeFile;
    tempLink.setAttribute('download', 'NeelB_Resume.pdf');

    document.body.appendChild(tempLink);
    tempLink.click();

    document.body.removeChild(tempLink);
  };
  
    const instagramUrl = "https://www.instagram.com/yunoneelb/"; 
    const linkedinUrl = "https://www.linkedin.com/in/neelanjan-barman/";
    const githubUrl = "https://github.com/BeyondNeel";
    const youtubeUrl = "https://www.youtube.com/channel/UCR4Pl2A-z42xqYyai7k3OTA";
    const twitterUrl = "https://twitter.com/i/flow/login?redirect_after_login=%2F";

  React.useEffect(() => {
    const typed = new Typed(el.current, {
      strings: ['Developer.', 'Graphics Designer.', 'Video Editor.', 'Storyteller.', 'Content Creator.'],
      typeSpeed: 60,
      loop: true,
    });

    return () => {
      typed.destroy();
    };
  }, []);

  const scrollContainerRef = useRef(null);

  useEffect(() => {
    const scrollContainer = scrollContainerRef.current;

    if (scrollContainer) {
      scrollContainer.addEventListener("wheel", (evt) => {
        evt.preventDefault();
        scrollContainer.scrollLeft += evt.deltaY;
        scrollContainer.computedStyleMap.scrollBehavior = "auto";
      });
    }
  }, []);

  return (
    <m.div initial={{ opacity: "0" }} 
    animate={{ opacity: "1" }} 
    transition={{ duration: 1, ease: "easeOut" }} 
    className={darkMode ? "dark" : ""}>
      <Head>
        <title>NeelB - Portfolio 🎧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.4.0/fonts/remixicon.css" rel="stylesheet"></link>
        <link rel="stylesheet" href="./globals.css" />
      </Head>
      <main className=" bg-white px-10 dark:bg-black md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <m.h1 initial={{ y: "100%" }} 
            animate={{ y: "0%" }} 
            transition={{ delay: 0.1, duration: 0.75, ease: "easeOut" }} 
            exit={{ opacity: 1 }} 
            className="font-burtons text-xl">developed by NeelB 𓆩🖤𓆪</m.h1>
            <m.ul initial={{ y: "100%" }} 
            animate={{ y: "0%" }} 
            transition={{ delay: 0.1, duration: 0.75, ease: "easeOut" }} 
            exit={{ opacity: 1 }} 
            className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-3xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-300 text-white px-3.5 py-2 border-none rounded-md ml-6"
                  href="#"
                  onClick={handleResumeDownload}
                >
                  Resume
                </a>
              </li>
              <li>
              <Link href="/gateway">
                <span className="bg-gradient-to-r from-cyan-500 text- to-teal-300 text-white px-3.5 py-2 border-none rounded-md ml-6">
                <i class="ri-ancient-gate-line"></i>
                </span>
              </Link>
              </li>
            </m.ul>
          </nav>
          <div className="text-center p-10 py-10">
            <m.h2 initial={{ y: "100%" }} 
            animate={{ y: "0%" }} 
            transition={{ duration: 1.2, ease: "easeOut" }} 
            exit={{ opacity: 1 }} 
            className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-300 md:text-6xl">
              Neelanjan Barman
            </m.h2>
            <m.h3 initial={{ x: "100%" }} 
            animate={{ x: "0" }} 
            transition={{ duration: 1.4, ease: "easeOut" }} 
            exit={{ opacity: 1 }} 
            className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer..
            </m.h3>
            <span ref={el} className="text-teal-600 front-small dark:text-teal-300 md:text-5xl"/>
            <m.p initial={{ y: "100%" }} 
            animate={{ y: "0%" }} 
            transition={{ duration: 1.2, ease: "easeOut" }} 
            exit={{ opacity: 1 }} 
            className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Currently, I am pursuing B.Tech in Computer Science Engineering from
              NIT Kolkata. I'm very passionate to be a part of an organization that
              would make me more resourceful and innovative. 
              Connect with me through the socials provided below!
            </m.p>
            <m.div initial={{ y: "100%" }} 
            animate={{ y: "0%" }} 
            transition={{ delay: 0.2, duration: 1.2, ease: "easeOut" }} 
            exit={{ opacity: 1 }} 
            className="icons text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href={instagramUrl} target="_blank" rel="noopener noreferrer">
              <AiFillInstagram className="cursor-pointer" />
            </a>
            <a href={linkedinUrl} target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin className="cursor-pointer"/>
            </a>
            <a href={githubUrl} target="_blank" rel="noopener noreferrer">
              <AiFillGithub className="cursor-pointer"/>
            </a>
            <a href={youtubeUrl} target="_blank" rel="noopener noreferrer">  
              <AiFillYoutube className="cursor-pointer"/>
            </a>
            <a href={twitterUrl} target="_blank" rel="noopener noreferrer">
              <AiFillTwitterCircle className="cursor-pointer"/>
            </a>
            </m.div>
            <m.div initial={{ y: "100%" }}  
              animate={isRotated ? { y: "0%", rotate: 360 } : { y: "0%", rotate: 0 }}
              transition={{ duration: 1.2, ease: "easeOut" }} 
              exit={{ opacity: 1 }}
              whileTap={{ rotate: 360 }}
              onTap={() => setIsRotated(!isRotated)}
              className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 cursor-pointer">
              <Image src={devNeelB} layout="fill" objectFit="cover" />
            </m.div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-4xl py-1 dark:text-white ">Education ⛩️</h3>
            <div className="box">
            <div className="vertical">
            <div className="vtext1 text-xl text-gray-700 dark:text-gray-100">
                B.Tech 
                <br></br>
                <span className="text-lg text-gray-500 dark:text-gray-400">
                  Narula Institute of Technology
                </span> 
              </div>
              <div className="vdesc1 text-gray-500 dark:text-gray-400">
                2020-2024
              </div>
            </div>
            <div className="vertical">
            <div className="vtext1 text-xl text-gray-700 dark:text-gray-100">
                12th 
                <br></br>
                <span className="text-lg text-gray-500 dark:text-gray-400">
                Kendriya Vidyalaya CoochBehar
                </span> 
              </div>
              <div className="vdesc1 text-gray-500 dark:text-gray-400">
                2020              
              </div>
            </div>
            <div className="vertical">
            <div className="vtext1 text-xl text-gray-700 dark:text-gray-100">
                10th
                <br></br>
                <span className="text-lg text-gray-500 dark:text-gray-400">
                Kendriya Vidyalaya CoochBehar
                </span> 
              </div>
              <div className="vdesc1 text-gray-500 dark:text-gray-400">
                2018
              </div>
            </div>
            </div>
          </div>          
          <div className="card lg:flex gap-10">
            <div className="card1 text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-900 flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600 dark:text-teal-300">
                Guide - VOL. I
              </h3>
              <p className="py-2 text-black dark:text-gray-300">
                Hi there! thanks for visiting this site, I'm going to give you a quick roadmap here,
                at the top right you can see a crescent moon like icon, by tapping it,
                you can alter between the dark and light theme, and just beside it you can see a resume button,
                by tapping it, you can download the respective pdf file.
              </p>
            </div>
            <div className="card2 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-900 flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600 dark:text-teal-300">
                Guide - VOL. II
              </h3>
              <p className="py-2 text-black dark:text-gray-300">
              Lets continue from where we left, 
              so beside resume, you can see a Gate like icon, 
              on tapping it you'll be redirected to the projects section, 
              there you can find many mini projects. Now, back to the portfolio, 
              you can see many social media handle icons, 
              by tapping it, you'll be redirected to my respective social profiles.
              </p>
            </div>
            <div className="card3 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-900 flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600 dark:text-teal-300">Guide - VOL. III</h3>
              <p className="py-2 text-black dark:text-gray-300">
              You can see a character made by me in a circular frame, 
              tap on it to rotate. Now, below the Guided vols you can see certificates, 
              scroll vertically over it to scroll through the certificates, 
              to scroll further just scroll vertically outside the certificate region. 
              That’s it, a quick roadmap, the rest you can figure it yourself easily. 
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-4xl py-1 dark:text-white ">Certificates 🔮</h3>
            <hr className="hr1 w-auto border-teal-400"></hr>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Hello, I hope you are doing well
              <span className="text-teal-500 dark:text-teal-300"> 🎐 visitor</span>.
               Below are some of my<span className="text-teal-500 dark:text-teal-300"> certificates</span>.
               <span className="text-red-500 dark:text-red-500"> NOTE: Scroll vertically over the certificate region to scroll through the certificates, to scroll down futher just scroll vertically outside the certificate region.<span className="text-black dark:text-gray-200"> You can <span className="text-teal-500 dark:text-teal-300">download</span> the certificates by tapping on it.</span></span>
            </p>
          </div>
          <br></br>
          <div className="certificate">
          <div className="gallery-wrap">
    <div className="gallery" ref={scrollContainerRef}>
      <div>
      <a href={web1} download="AWS-certificate.pdf">
        <span>
          <Image src={web1}/>
        </span>
       </a>
       <a href={web2} download="DSA-certificate.pdf"> 
        <span>
          <Image src={web2} />
        </span>
        </a>
        <a href={web3} download="WebDev-Python-certificate.pdf">  
        <span>
          <Image src={web3} />
        </span>
        </a>
      </div>
      <div>
      <a href={web4} download="ProblemSolving-certificate.pdf">  
        <span>
          <Image src={web4} />
        </span>
        </a>
        <a href={web5} download="CyberSecurity-certificate.pdf">
        <span>
          <Image src={web5} />
        </span>
        </a>
        <a href={web6} download="AndroidApp-certificate.pdf">
        <span>
          <Image src={web6} />
        </span>
        </a>
      </div>
    </div>
  </div>
  </div>
        </section>  
      </main>   
      <div id="page">
        <a href= {githubUrl} target="_blank" rel="noopener noreferrer">
            <div class="page-inner">
                <h1>Github</h1>
                <i class="ri-arrow-right-up-line"></i>
                <div class="center"></div>
            </div>
        </a>
        <a href= {linkedinUrl} target="_blank" rel="noopener noreferrer">
            <div class="page-inner">
                <h1>LinkedIn</h1>
                <i class="ri-arrow-right-up-line"></i>
                <div class="center"></div>
            </div>
        </a>
        <a href= {instagramUrl} target="_blank" rel="noopener noreferrer">
            <div class="page-inner">
                <h1>Instagram</h1>   
                <i class="ri-arrow-right-up-line"></i>
                <div class="center"></div>
            </div>
        </a>
      </div>
      <footer>
        <div className="footer text-gray-400 dark:text-gray-400">
          <div className="footerFirst">
            <span className="footerspan">NeelB's Developer Portfolio</span><br></br>
            Copyright © 2023 <Link href="/"><span className="cursor-pointer hover:text-teal-300">neelb.in</span></Link> | All rights reserved ®
          </div>
        </div>
      </footer>
    </m.div>
  );
}
