import React from "react";
import Link from "next/link";
import Head from "next/head";

const GateWay = () => {

  return (
    <div className="video-container">
    <Head>
      <title>NeelB - Portfolio 🎧</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="./globals.css" />
    </Head>
    <video
      autoPlay
      loop
      muted
      className="video-background"
    >
      <source src="bg3.webm" type="video/webm" />
    </video>
    <div className="center-button">
      <Link href="https://musify-neelb.netlify.app/">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Musify 🎵</span>
        </button>
      </Link>
      <Link href="https://snake-neelb.netlify.app/">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Snake 🐍</span>
        </button>
      </Link>
      <Link href="https://calculator-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Calculator 🔮</span>
        </button>
      </Link>
      <Link href="https://cheatsheet-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Cheetsheet 📄</span>
        </button>
      </Link>
      <Link href="https://tictactoe-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">TicTacToe 🎮</span>
        </button>
      </Link>
      <br></br>
      <br></br>
      <br></br>
      <Link href="https://clock-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Clock 🕒</span>
        </button>
      </Link>
      <Link href="/">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Portfolio 🖤</span>
        </button>
      </Link>
      <Link href="https://neelb-magma-clone.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Magma 🌐</span>
        </button>
      </Link>
      <Link href="/secret">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Secret txt 🤫</span>
        </button>
      </Link>
      <Link href="/reasons-to-live">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Reasons to live🗿</span>
        </button>
      </Link>
      <br></br>
      <br></br>
      <br></br>
      <Link href="https://aspect-ratio-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Aspect Ratio Calc 🧮</span>
        </button>
      </Link>
      <Link href="https://forms-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Multi Step Forms 📝</span>
        </button>
      </Link>
      <Link href="https://github-api-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Github API 😺</span>
        </button>
      </Link>
      <Link href="https://headtail-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Heads Tails 🟡</span>
        </button>
      </Link>
      <br></br>
      <br></br>
      <br></br>
      <Link href="https://color-picker-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Color Picker 🎨</span>
        </button>
      </Link>
      <Link href="https://battery-status-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Live Battery Status 🔋</span>
        </button>
      </Link>
      <Link href="https://movies-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Movies Info 🎥</span>
        </button>
      </Link>
      <Link href="https://netspeed-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Internet Speed 🏎️</span>
        </button>
      </Link>
      <br></br>
      <br></br>
      <br></br>
      <Link href="https://passwords-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Passwords 🔑</span>
        </button>
      </Link>
      <Link href="https://pixelart-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Pixel Art 👾</span>
        </button>
      </Link>
      <Link href="https://pong-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Pong 🏓</span>
        </button>
      </Link>
      <Link href="https://todo-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">ToDoS 📝</span>
        </button>
      </Link>
      <Link href="https://type-test-neelb.netlify.app">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">Type Speed ⌨️</span>
        </button>
      </Link>
    </div>
  </div>
  );
};

export default GateWay;
