import React from "react";
import Link from "next/link";
import Head from "next/head";

const SecretMsg = () => {
  return (
    <div className="video-container">
      <Head>
        <title>NeelB - Portfolio 🎧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./globals.css" />
      </Head>
      <video
        autoPlay
        loop
        muted
        className="video-background"
      >
        <source src="bg5.webm" type="video/webm" />
      </video>
      <div className="center-button">
        <Link href="/portfolio">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">
            1. Eating you favorite food.
            <br></br>
            2. The excitement of the fairs.
            <br></br>
            3. Vacations with your family.
            <br></br>
            4. Getting your first car.
            <br></br>
            5. Graduating highschool.
            <br></br>
            6. Getting into a good college.
            <br></br>
            7. Graduating college.
            <br></br>
            8. Starting your new career path.
            <br></br>
            9. Birthdays.
            <br></br>
            10. The smell of winter.
            <br></br>
            11. Hanging out with friends.
            <br></br>
            12. Job promotions.
            <br></br>
            13. Pumpkin Pie.
            <br></br>
            14. Thanksgiving Dinner.
            <br></br>
            15. Halloween.
            <br></br>
            16. Movies.
            <br></br>
            17. Sleep overs.
            <br></br>
            18. Catching your dreams.
            <br></br>
            19. Binge watching on Netflix.
            <br></br>
            20. Homecoming.
            <br></br>
            21. 2-3am talks with someone.
            <br></br>
            22. The smell of coffee in the morning.
            <br></br>
            23. Singing in the shower.
            <br></br>
            24. Imagination.
            <br></br>
            25. snow ball fights.
            <br></br>
            26. Adventures.
            <br></br>
            <span></span>
          </span>
        </button>
        </Link>
        <br></br>
        <br></br>
      </div>
    </div>
  );
};

export default SecretMsg;
