import React from "react";
import Link from "next/link";
import Head from "next/head";

const SecretMsg = () => {
  return (
    <div className="video-container">
      <Head>
        <title>NeelB - Portfolio 🎧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./globals.css" />
      </Head>
      <video
        autoPlay
        loop
        muted
        className="video-background"
      >
        <source src="bg4.webm" type="video/webm" />
      </video>
      <div className="center-button">
        <button className="bt1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
          <span className="text-white">
            1. The best way to cheer yourself up is to try to cheer
            somebody else up.
            <br></br>
            2. Smile in the mirror. Do that every morning, and you'll start to
            see a big difference in your life.
            <br></br>
            3. The most wasted of all days is one without laughter.
            <br></br>
            4. A smile is happiness you'll find right under your nose.
            <br></br>
            5. When life gives you a hundred reasons to cry, show life that you
            have a thousand reasons to smile.
            <br></br>
            6. Today, give a stranger one of your smiles. It might be the only
            sunshine he sees all day.
            <br></br>
            7. Keep smiling, because life is a beautiful thing and there's so
            much to smile about.
            <br></br>
            8. A smile is a curve that sets everything straight.
            <br></br>
            9. Your smile will give you a positive countenance that will make
            people feel comfortable around you.
            <br></br>
            10. A smile is the light in your window that tells others that there
            is a caring, sharing person inside.
            <br></br>
            <span></span>
          </span>
        </button>
        <br></br>
        <br></br>
        <Link href="/reasons-to-live">
          <button className="btn1 px-5 py-3 border-none rounded-md ml-6 hover:text-lg">
            <span className="text-white">Tap Me ⛩️</span>
          </button>
        </Link>
      </div>
    </div>
  );
};

export default SecretMsg;
